-- Import 50 diverse user profiles
-- Run this in Supabase SQL Editor after importing users_import.csv

INSERT INTO profiles (user_id, name, email, profile_picture, linkedin_url, background, expertise, looking_for, open_to, opted_in, imported_from, created_at, updated_at)
VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Sarah Chen', 'sarah.chen@email.com', NULL, 'https://linkedin.com/in/sarahchen', 'Senior software engineer with 8 years experience building scalable web applications. Led development of microservices architecture serving 5M+ users at Series B SaaS startup. Strong full-stack background with React and Node.js. Previously at Google working on Cloud Platform APIs.', 'Full-stack development, React, Node.js, TypeScript, PostgreSQL, AWS, Kubernetes, microservices architecture, API design, system design, team leadership, agile methodologies, CI/CD pipelines', '["A cofounder", "Domain expertise"]'::jsonb, '["Providing domain expertise", "Mentoring"]'::jsonb, true, 'csv_import', '2025-01-15 10:00:00', '2025-01-15 10:00:00'),

('550e8400-e29b-41d4-a716-446655440002', 'Michael Rodriguez', 'michael.rodriguez@email.com', NULL, 'https://linkedin.com/in/michaelrodriguez', 'Product designer with 6 years experience at early-stage startups. Led design for mobile app that reached 2M downloads. Expert in user research, prototyping, and building design systems from scratch. Passionate about accessible and inclusive design.', 'UX/UI design, Figma, user research, prototyping, design systems, mobile design, accessibility, information architecture, design thinking, usability testing, visual design, interaction design', '["A cofounder", "Introductions"]'::jsonb, '["Being a cofounder for the right fit", "Providing domain expertise", "Making introductions"]'::jsonb, true, 'csv_import', '2025-01-15 10:01:00', '2025-01-15 10:01:00'),

('550e8400-e29b-41d4-a716-446655440003', 'Emily Thompson', 'emily.thompson@email.com', NULL, NULL, 'Product manager with 7 years experience shipping B2B SaaS products. Led product strategy at Series A startup that achieved $10M ARR. Strong background in customer development and data-driven decision making. MBA from Stanford GSB.', 'Product management, product strategy, roadmap planning, customer development, data analysis, SQL, A/B testing, market research, stakeholder management, agile methodologies, OKRs, feature prioritization', '["Domain expertise", "Mentorship"]'::jsonb, '["Providing domain expertise", "Mentoring", "Making introductions"]'::jsonb, true, 'csv_import', '2025-01-15 10:02:00', '2025-01-15 10:02:00'),

('550e8400-e29b-41d4-a716-446655440004', 'James Patel', 'james.patel@email.com', NULL, 'https://linkedin.com/in/jamespatel', 'Climate tech entrepreneur with 5 years building clean energy solutions. Founded solar installation startup that deployed 500+ systems. Deep expertise in renewable energy markets, energy storage, and climate policy. Previously energy analyst at Department of Energy.', 'Climate technology, renewable energy, solar energy, energy storage, battery technology, climate policy, carbon markets, sustainability, environmental impact assessment, energy economics, project finance, regulatory compliance', '["A cofounder", "Domain expertise"]'::jsonb, '["Being a cofounder for the right fit", "Providing domain expertise"]'::jsonb, true, 'csv_import', '2025-01-15 10:03:00', '2025-01-15 10:03:00'),

('550e8400-e29b-41d4-a716-446655440005', 'Olivia Kim', 'olivia.kim@email.com', NULL, 'https://linkedin.com/in/oliviakim', 'Data scientist with 6 years experience building ML models for production. Built recommendation systems and predictive models at Netflix and Spotify. Expert in deep learning, NLP, and MLOps. PhD in Computer Science from MIT focused on machine learning.', 'Machine learning, deep learning, Python, TensorFlow, PyTorch, natural language processing, computer vision, MLOps, data engineering, statistical modeling, A/B testing, data visualization, big data, Spark, SQL', '["Domain expertise", "Introductions"]'::jsonb, '["Providing domain expertise", "Mentoring"]'::jsonb, true, 'csv_import', '2025-01-15 10:04:00', '2025-01-15 10:04:00');

-- Verify import
SELECT COUNT(*) as imported_profiles FROM profiles WHERE imported_from = 'csv_import';

